# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.PositiveSmallIntegerField()),
                ('model_code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('front', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('back', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('neck', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('arm', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, default='', max_length=3000, null=True)),
                ('client', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('old_code_parent', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models.Family')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models.Line')),
                ('parent', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='models.Model')),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='model',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models.Sex'),
        ),
    ]
